import './globals.css'
import type { Metadata } from 'next'
import GoogleMapsScriptLoader from '@/components/GoogleMapsScriptLoader'
import { ClientProviders } from './ClientProviders'

export const metadata: Metadata = {
  title: 'Lets Go Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <body className="font-museo">
        <ClientProviders>
          <GoogleMapsScriptLoader />
          {children}
        </ClientProviders>
      </body>
    </html>
  )
}
